### ISSUE TITLE
Extruder Heat Problem

### ISSUE THREAD

**Issue by PeteyPub** [avluis/Marlin#1]
After the newest update I cannot seem to heat up my extruder. Bed takes forever to heat up, waited 30 minutes to get to 56*. I'm using Repetier trying to print the Servo mount for auto leveling from Thingieverse...

UPDATE!!

After reflashing the firmware twice I got the hot end to heat up again... Not sure what caused a snag. Maybe it was software related. Rambo needed to take a break for a few minutes i guess...

**Comment by avluis** [comment]
Are you still having any issues related to heat level?

If you don't mind, can you tell me about your system:
Windows, OS X, Linux (flavor), etc.
If anything, it could always be a setting from your EEPROM still saved that needs to be cleared or simply an Arduino avrdude issue that, as you mentioned, resolved itself.

Let me know if you encounter any other issues.
I will leave this issue open for a while unless the issue repeats itself.
